### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by akbasferhat** [agasking1337/steam-auto-comment#2]
C:\Users\woxleader\Desktop\steam-auto-comment-master\steam-rep-bot>node index.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'C:\Users\woxleader\Desktop\steam-auto-comment-master\
steam-rep-bot\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772
:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:677:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)[39m

[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

C:\Users\woxleader\Desktop\steam-auto-comment-master\steam-rep-bot>

**Comment by ovykun1121** [comment]
> C:\Users\woxleader\Desktop\steam-auto-comment-master\steam-rep-bot>node index.js
> 
> internal/modules/cjs/loader.js:775
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\woxleader\Desktop\steam-auto-comment-master
> steam-rep-bot\index.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772
> :15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:677:27)�[39m
> �[90m at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)�[39m
> 
> �[90m at internal/main/run_main_module.js:17:11�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }
> 
> C:\Users\woxleader\Desktop\steam-auto-comment-master\steam-rep-bot>

I'd like to know how to fix this, too...

**Comment by agasking1337** [comment]
hi! try to reinstall all the modules
